# Generated by Django 3.2 on 2022-05-16 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hlis.custom_auth.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('expiration_time', models.DateTimeField(default=hlis.custom_auth.utils.forgot_password_expiration_time)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forgot Password Id',
            },
        ),
    ]
