# Generated by Django 3.2 on 2022-05-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20220517_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='user_hashtag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='user_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
